### ISSUE TITLE
Http Comands

### ISSUE THREAD

**Issue by olive2006** [pepitooo/naim-uniti-remote#2]
Hello,

First sorry for my bad english. Can you please say me where can i find the http commands for the uniti series. Big Thanks

Tolga

**Comment by pepitooo** [comment]
Hello, 

You will find the http command inside the source code on the small script named naim-uniti.py

As i described, there is no official list of command or API, so I reversed engineered it, and only the one I needed.

**Comment by rogierdejong** [comment]
And out of curiosity, how did that reverse engineering work? Eager to learn!

**Comment by pepitooo** [comment]
I used some basic linux tools, tcpdump, ngrep.
By sniffing what was passing from my phone via naim app to the naim device.

**Comment by rogierdejong** [comment]
Good stuff! Thanks for sharing

**Comment by olive2006** [comment]
Hi @pepitooo,

First thanks for your help. But i have a problem, when i send this comman http://192.168.1.110:15081/inputs/tidal?cmd=select it dont change the input. For analog and digital it works. Can you please say me what is wrong.

**Comment by pepitooo** [comment]
Hello @olive2006,

After checking, I'm sorry, but tidal source files are not consider as a real input.

There is not call to choose tidal input, but instead, it using a system of playlist.
It load a playlist using tidal information and start to play in an unique http post
```POST /inputs/playqueue?where=end&clear=true&current=0&play=true```

So this small tool will not be able to switch to Tidal, Spotify or music service should behave the same way.

**Comment by olive2006** [comment]
Hello @pepitooo,

Thanks for your answer, i have also problem with the commands previous and left. Do you know the http commands for this. It is not the same command like next and right. Sorry when i disturb you. Thanks

**Comment by pepitooo** [comment]
The program do same call as the ios/android app to control Naim device, NOT the remote control.

```GET /nowplaying?cmd=next```
```GET /nowplaying?cmd=prev```

Previous command will first start from the begin of the track then if you call it a second time (quickly after) will go the the previous track in the list.

By using the program you will avoid mistakes
```python naim-uniti.py --ip 192.168.xxx.yyy play-next```
```python naim-uniti.py --ip 192.168.xxx.yyy play-previous```

or do some curl call if you prefer
```curl -X GET http://192.168.xxx.yyy:15081/nowplaying?cmd=next```
```curl -X GET http://192.168.xxx.yyy:15081/nowplaying?cmd=prev```

**Comment by olive2006** [comment]
Thanks @pepitooo
